[audiobookshelf]
digest = 'sha256:a52dc5db694a5bf041ce38f285dd6c6a660a4b1b21e37ad6b6746433263b2ae5'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.32.1'
versioning = 'semver'

[ente-museum]
digest = 'sha256:691aa3344eb6698a6a6b00abad64bcb6bc97f939a92d78970d53a502db17a305'
image = 'ente-io/server'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[ente-postgresql]
digest = 'sha256:5fe8ca7fc662071188c30271cb870d1ce9a6ec4578c934b064697ae77a9241e1'
image = 'library/postgres'
registry = 'docker.io'
version = '15.16-alpine'
versioning = 'regex:^(?<major>15)\.(?<minor>\d+)-alpine$'

[ente-web]
digest = 'sha256:3a36ff18d873946a29ff22b26bf0f8c0399e3dd08a9ed9ce8f0c01911f40e3e5'
image = 'ente-io/web'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[gluetun]
digest = 'sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.41.1'
versioning = 'semver'

[grist]
digest = 'sha256:93dd0f7b97a7864cd0a9101a283385e30754dd5ee0e967ba95a8c19caae43056'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.10'
versioning = 'semver'

[homeassistant]
digest = 'sha256:3e2dff545c46e91f4ab2b21597016011d76d0de58bc8eaf51d75e841f337bf88'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2026.2.2'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:035b9ab53cfa147d7202b61f5f7782b939ae815b7d6bc81c96b7b42ff1fca950'
image = 'library/postgres'
registry = 'docker.io'
version = '18.2-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:b213fa3c82d27a21a299c46ffbb38a091f18384db1ad67d409a3b34fe0fce556'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v2.5.6'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:aa163d2e1cc2b16a9515dd1fef901e6f5231befad7024f093d7be1f2da14341a'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v2.5.6'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[jellyfin]
digest = 'sha256:333b647716631443a43c7fabac4b0c46b4e2f036bad19547e00958f10f721b85'
image = 'jellyfin/jellyfin'
registry = 'docker.io'
version = '10.11.6'
versioning = 'semver'

[librechat-server]
digest = 'sha256:1e9ffe435b56412f7bf41148673e5594ecb067a3cc3991925d1cc2222db7e2a7'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.2'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:474f5c3bf0e355bb97dafda730e725169a4d51c5578abf7be9ec7ad3fdee4481'
image = 'library/mongo'
registry = 'docker.io'
version = '8.2.5'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:293ebcfdc7118a8e7b67e569ccc278bd07e999e9718ce3c8bfa5bdbcafa40e88'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:5de2adcfae90da9ad37304d1a5c9378b0a574b246aa2c2acda7ae5eee368f3bd'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.1-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mamapi]
digest = 'sha256:9403628e9c0e773c04bb640743105bdbfca53423033828e13d3f5efc79370493'
image = 'elforkhead/mamapi'
registry = 'ghcr.io'
version = 'v2.1.2'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:6138b1e2f7262e28c0d44548766cac05d6d60b1d8efc3279722629894c3b35f2'
image = 'foxxmd/multi-scrobbler'
registry = 'docker.io'
version = '0.11.4'
versioning = 'semver'

[paperless-postgresql]
digest = 'sha256:035b9ab53cfa147d7202b61f5f7782b939ae815b7d6bc81c96b7b42ff1fca950'
image = 'library/postgres'
registry = 'docker.io'
version = '18.2-alpine'
versioning = 'docker'

[paperless-redis]
digest = 'sha256:fd83658b0e40e2164617d262f13c02ca9ee9e1e6b276fd2fa06617e09bd5c780'
image = 'library/redis'
registry = 'docker.io'
version = '8.6.0-alpine'
versioning = 'docker'

[paperless-server]
digest = 'sha256:7b937cb2fa2885ab0ecfceb8c7e8827e2312472d9d897a270097ba7f5522dcdc'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.20.7'
versioning = 'semver'

[prowlarr]
digest = 'sha256:e74a1e093dcc223d671d4b7061e2b4946f1989a4d3059654ff4e623b731c9134'
image = 'linuxserver/prowlarr'
registry = 'docker.io'
version = '2.3.0'
versioning = 'semver'

[shelfmark]
digest = 'sha256:acdab66e8f2ec6820365be8fc17aa3218d3b28556e074633a9c381d317937418'
image = 'calibrain/shelfmark-lite'
registry = 'ghcr.io'
version = 'v1.1.0'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:85eb27d2d09cd4cb748036a4c7f261321da516b6f88229176cf05a92ccd26815'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.1.4'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[radarr]
digest = 'sha256:6d3e68474ea146f995af98d3fb2cb1a14e2e4457ddaf035aa5426889e2f9249c'
image = 'linuxserver/radarr'
registry = 'docker.io'
version = '6.0.4'
versioning = 'semver'

[recyclarr]
digest = 'sha256:2550848d43a453f2c6adf3582f2198ac719f76670691d76de0819053103ef2fb'
image = 'recyclarr/recyclarr'
registry = 'ghcr.io'
version = '7.5.2'
versioning = 'semver'

[sabnzbd]
digest = 'sha256:1a26f56dfc047b62d5ddc20bc92bdebfbe7c3cb58d2d3523958838a09182d77a'
image = 'linuxserver/sabnzbd'
registry = 'docker.io'
version = '4.5.5'
versioning = 'semver'

[sonarr]
digest = 'sha256:37be832b78548e3f55f69c45b50e3b14d18df1b6def2a4994258217e67efb1a1'
image = 'linuxserver/sonarr'
registry = 'docker.io'
version = '4.0.16'
versioning = 'semver'

[zigbee2mqtt]
digest = 'sha256:89cf02f379aa743a68494388e3a26fba7b8c9101f8b452038cc07aeff3fc983c'
image = 'koenkk/zigbee2mqtt'
registry = 'docker.io'
version = '2.8.0'
versioning = 'semver'