[audiobookshelf]
digest = 'sha256:a52dc5db694a5bf041ce38f285dd6c6a660a4b1b21e37ad6b6746433263b2ae5'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.32.1'
versioning = 'semver'

[ente-museum]
digest = 'sha256:04e9b1e2e9eacf1c4a2d5055ca4cdc23b7548ed74c45f3ef3487d97f327a419e'
image = 'ente-io/server'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[ente-postgresql]
digest = 'sha256:b3968e348b48f1198cc6de6611d055dbad91cd561b7990c406c3fc28d7095b21'
image = 'library/postgres'
registry = 'docker.io'
version = '15.15-alpine'
versioning = 'regex:^(?<major>15)\.(?<minor>\d+)-alpine$'

[ente-web]
digest = 'sha256:501ea3bbcb3cf12090a4c8c07a1070b89a7daa66ecd59c7b1198a3c7496a5a8f'
image = 'ente-io/web'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[gluetun]
digest = 'sha256:6b54856716d0de56e5bb00a77029b0adea57284cf5a466f23aad5979257d3045'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.41.0'
versioning = 'semver'

[grist]
digest = 'sha256:93dd0f7b97a7864cd0a9101a283385e30754dd5ee0e967ba95a8c19caae43056'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.10'
versioning = 'semver'

[homeassistant]
digest = 'sha256:3007eeeaf87d1e3a2047faeac6ff01dfef218b8a404bdff3ce421c1f4f363a43'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2026.1.2'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:b40d931bd0e7ce6eecc59a5a6ac3b3c04a01e559750e73e7086b6dbd7f8bf545'
image = 'library/postgres'
registry = 'docker.io'
version = '18.1-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:b3deefd1826f113824e9d7bc30d905e7f823535887d03f869330946b6db3b44a'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v2.4.1'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:e6a6298e67ae077808fdb7d8d5565955f60b0708191576143fc02d30ab1389d1'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v2.4.1'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[jellyfin]
digest = 'sha256:6d819e9ab067efcf712993b23455cc100ee5585919bb297ea5a109ac00cb626e'
image = 'jellyfin/jellyfin'
registry = 'docker.io'
version = '10.11.5'
versioning = 'semver'

[librechat-server]
digest = 'sha256:36cf6811bc2461ada6879ab299ce32efebfe8b8e0155334161935d72747b9a2e'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.1'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:d6b569590880bca35e43318418133a426b024bcb649eeb63bb071bc1490bee41'
image = 'library/mongo'
registry = 'docker.io'
version = '8.2.3'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:293ebcfdc7118a8e7b67e569ccc278bd07e999e9718ce3c8bfa5bdbcafa40e88'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:d708f9df030dbd0d7c3d67d349be21acb786d263a5fd92fc12d7b5d2dba49816'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.1-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mamapi]
digest = 'sha256:9403628e9c0e773c04bb640743105bdbfca53423033828e13d3f5efc79370493'
image = 'elforkhead/mamapi'
registry = 'ghcr.io'
version = 'v2.1.2'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:489684af568507ab33de0befd1138cd5c815b2fa6c728ab968516053495d609f'
image = 'foxxmd/multi-scrobbler'
registry = 'docker.io'
version = '0.11.0'
versioning = 'semver'

[paperless-postgresql]
digest = 'sha256:b40d931bd0e7ce6eecc59a5a6ac3b3c04a01e559750e73e7086b6dbd7f8bf545'
image = 'library/postgres'
registry = 'docker.io'
version = '18.1-alpine'
versioning = 'docker'

[paperless-redis]
digest = 'sha256:6cbef353e480a8a6e7f10ec545f13d7d3fa85a212cdcc5ffaf5a1c818b9d3798'
image = 'library/redis'
registry = 'docker.io'
version = '8.4.0-alpine'
versioning = 'docker'

[paperless-server]
digest = 'sha256:06ca6a6c2a21cfebcc7c5f2e0d38f892dba4bcb090b8781a55d003c63cce386a'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.20.4'
versioning = 'semver'

[prowlarr]
digest = 'sha256:d3e9307b320b6772749a2cf8fc2712e9e824c4930b034680ad4d08a9e2f25884'
image = 'linuxserver/prowlarr'
registry = 'docker.io'
version = '2.3.0'
versioning = 'semver'

[shelfmark]
digest = 'sha256:85adbbce1eb36ff32bd9ff36fbbd1720a7bd00ca1b592427b9a07b4b3f198a3d'
image = 'calibrain/shelfmark-lite'
registry = 'ghcr.io'
version = '1.0.3'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:95114034a7f74672b76f795f6938921b0ca795f85b59b48691035dc66714f34c'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.1.4'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[radarr]
digest = 'sha256:270f25698624b57b86ca119cc95399d7ff15be8297095b4e1223fd5b549b732c'
image = 'linuxserver/radarr'
registry = 'docker.io'
version = '6.0.4'
versioning = 'semver'

[recyclarr]
digest = 'sha256:2550848d43a453f2c6adf3582f2198ac719f76670691d76de0819053103ef2fb'
image = 'recyclarr/recyclarr'
registry = 'ghcr.io'
version = '7.5.2'
versioning = 'semver'

[sabnzbd]
digest = 'sha256:a46e75d861e6b26d7ee263b22743d6fdaaa4a5ccd42168b6ea563a2f047d9438'
image = 'linuxserver/sabnzbd'
registry = 'docker.io'
version = '4.5.5'
versioning = 'semver'

[sonarr]
digest = 'sha256:02b4d538d351d6e35882a021c08e8600fe95d28860fb1dd724b597166e7221ca'
image = 'linuxserver/sonarr'
registry = 'docker.io'
version = '4.0.16'
versioning = 'semver'

[zigbee2mqtt]
digest = 'sha256:60a295b40f4e7fb7ab4d995932369e50f2529837272fa4979e986ec1ffdb7fce'
image = 'koenkk/zigbee2mqtt'
registry = 'docker.io'
version = '2.7.2'
versioning = 'semver'