[audiobookshelf]
digest = 'sha256:6fbd7dc95d53c6e168ce69e760b87c334e3b9ba88bf7b8531ed5a116d5d6da03'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.30.0'
versioning = 'semver'

[core-keeper-server]
digest = 'sha256:6531227708c06db6850731609e2df3e0940e63149395c743f12a0ce5f0c34ead'
image = 'escaping/core-keeper-dedicated'
registry = 'docker.io'
version = 'v2.7.0'
versioning = 'semver'

[ente-museum]
digest = 'sha256:0135ea9d7e137283623f2cbb33ccf132b056f08bb8f9a9eb482f387db44f22e4'
image = 'ente-io/server'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[ente-postgresql]
digest = 'sha256:aa7b1ef595e165f0b780162e3a41edd0a7ed3ea672eb8a0f81615ba725e62bc5'
image = 'library/postgres'
registry = 'docker.io'
version = '15.15-alpine'
versioning = 'regex:^(?<major>15)\.(?<minor>\d+)-alpine$'

[ente-web]
digest = 'sha256:3a8bc317a9d813af2a0a4e32d705b9ec79d1fcd4e2d581b3b47e8d427f7ece41'
image = 'ente-io/web'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[gluetun]
digest = 'sha256:ef4a44819a60469682c7b5e69183e6401171891feaa60186652d292c59e41b30'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.40.3'
versioning = 'semver'

[grist]
digest = 'sha256:f9950aaed967201ac50d37fde12d55b05a9f530df789537460dad168aa6faf31'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.7'
versioning = 'semver'

[homeassistant]
digest = 'sha256:02f582ea7d25f41761282ac0965baf89f0009efed3ad92f8d7eaba5eb6ffd9a8'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2025.11.2'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:154ea39af68ff30dec041cd1f1b5600009993724c811dbadde54126eb10bedd1'
image = 'library/postgres'
registry = 'docker.io'
version = '18.1-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:379e31b8c75107b0af8141904baa8cc933d7454b88fdb204265ef11749d7d908'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v2.3.1'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:f8d06a32b1b2a81053d78e40bf8e35236b9faefb5c3903ce9ca8712c9ed78445'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v2.3.1'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[jellyfin]
digest = 'sha256:1edf3f17997acbe139718f252a7d2ded2706762390d787a34204668498dbc5f6'
image = 'jellyfin/jellyfin'
registry = 'docker.io'
version = '10.11.3'
versioning = 'semver'

[librechat-server]
digest = 'sha256:e6790a1fab2d1870efe077127cc6255cb58105cabde9ec013b8573bfe3025882'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.1-rc1'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:7245ffb851d149dbfac67397caf91bae4974d899972f9fd1d8985fc6eea3c13d'
image = 'library/mongo'
registry = 'docker.io'
version = '8.2.2'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:86a9b2202f740c1e737b4587de28faa81a131c4c616f832259bcea77096dd6a0'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:d708f9df030dbd0d7c3d67d349be21acb786d263a5fd92fc12d7b5d2dba49816'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.1-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mamapi]
digest = 'sha256:9403628e9c0e773c04bb640743105bdbfca53423033828e13d3f5efc79370493'
image = 'elforkhead/mamapi'
registry = 'ghcr.io'
version = 'v2.1.2'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:76c264aab69bbcfd647d2009562763bb6bc0d0d8fa0cd087a2c064cca265161b'
image = 'foxxmd/multi-scrobbler'
registry = 'docker.io'
version = '0.10.3'
versioning = 'semver'

[paperless-postgresql]
digest = 'sha256:154ea39af68ff30dec041cd1f1b5600009993724c811dbadde54126eb10bedd1'
image = 'library/postgres'
registry = 'docker.io'
version = '18.1-alpine'
versioning = 'docker'

[paperless-redis]
digest = 'sha256:8371f214b1c2792f9d9ef1077fe2ea37632c8ba087c962b7bc5d8d623aed686a'
image = 'library/redis'
registry = 'docker.io'
version = '8.4.0-alpine'
versioning = 'docker'

[paperless-server]
digest = 'sha256:719a4e4c4314b417646b00e58bfbfbe55e4cb59017a2dec1533e96d8deb66ec1'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.19.6'
versioning = 'semver'

[prowlarr]
digest = 'sha256:3dd3a316f60ea4e6714863286549a6ccaf0b8cf4efe5578ce3fe0e85475cb1cf'
image = 'linuxserver/prowlarr'
registry = 'docker.io'
version = '2.3.0'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:7034f73a3c6fa4ea40fd67df462939d1665d765231b572523921c98c2db5362e'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.1.2'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[radarr]
digest = 'sha256:e26fbfd3782520c0bb820666f041ca056acfe187a8b95214ee1f47512cc05a29'
image = 'linuxserver/radarr'
registry = 'docker.io'
version = '6.0.4'
versioning = 'semver'

[recyclarr]
digest = 'sha256:759540877f95453eca8a26c1a93593e783a7a824c324fbd57523deffb67f48e1'
image = 'recyclarr/recyclarr'
registry = 'ghcr.io'
version = '7.4.1'
versioning = 'semver'

[sabnzbd]
digest = 'sha256:0b4be872c3d937a8b0ba99e801dbc968d285ec413fdc4797a110b227ee8b1e64'
image = 'linuxserver/sabnzbd'
registry = 'docker.io'
version = '4.5.5'
versioning = 'semver'

[searxng]
digest = 'sha256:0124d32d77e0c7360d0b85f5d91882d1837e6ceb243c82e190f5d7e9f1401334'
image = 'searxng/searxng'
registry = 'docker.io'
version = '2025.11.29-c954e71f8'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d{1,2})\.(?<patch>\d{1,2})-(?<build>[a-z0-9]+)$'

[sonarr]
digest = 'sha256:4b8a853b76337cd5de5f69961e23b7d0792ce7bf0a8be083dd7202ef670bfc34'
image = 'linuxserver/sonarr'
registry = 'docker.io'
version = '4.0.16'
versioning = 'semver'

[zigbee2mqtt]
digest = 'sha256:3baac2a3b74a9945fbbcb665b3e6e0ace5df2d49b5502e3d26b66a5454316e81'
image = 'koenkk/zigbee2mqtt'
registry = 'docker.io'
version = '2.6.3'
versioning = 'semver'