[audiobookshelf]
digest = 'sha256:6fbd7dc95d53c6e168ce69e760b87c334e3b9ba88bf7b8531ed5a116d5d6da03'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.30.0'
versioning = 'semver'

[core-keeper-server]
digest = 'sha256:6531227708c06db6850731609e2df3e0940e63149395c743f12a0ce5f0c34ead'
image = 'escaping/core-keeper-dedicated'
registry = 'docker.io'
version = 'v2.7.0'
versioning = 'semver'

[ente-museum]
digest = 'sha256:0564d2432853fdb1f85a249678ecf3e7a65a77dbf78adec9ed6af920f0f9b199'
image = 'ente-io/server'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[ente-postgresql]
digest = 'sha256:64583b3cb4f2010277bdd9749456de78e5c36f8956466ba14b0b96922e510950'
image = 'library/postgres'
registry = 'docker.io'
version = '15.14-alpine'
versioning = 'regex:^(?<major>15)\.(?<minor>\d+)-alpine$'

[ente-web]
digest = 'sha256:9dc743414f4d5dce05539e0a04655095d3eddaa18c85edeb378fb2252216cac7'
image = 'ente-io/web'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[gluetun]
digest = 'sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.40.0'
versioning = 'semver'

[grist]
digest = 'sha256:bde50f4639b699cdeeb1ff58c4b7a79caa0e45098a9c8ed422fbb851be80f195'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.5'
versioning = 'semver'

[homeassistant]
digest = 'sha256:449140e073d8d7814098cd62dfdbb326ad043f51a3c4d4721889369f46751d52'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2025.10.4'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:48c8ad3a7284b82be4482a52076d47d879fd6fb084a1cbfccbd551f9331b0e40'
image = 'library/postgres'
registry = 'docker.io'
version = '18.0-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:590a76bba3d88ccf78b03cde0c0fb8788f7d76ae6caf90ad33a34b5b4cc35f11'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v2.2.1'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:2c951a4063b55ec2de197fdf6a85e32b05872d3a18a18eaf851b827ff2622814'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v2.2.1'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[jellyfin]
digest = 'sha256:c7dd335d455c95ad3fe7550824d93ceb911914bf4210e7899e11f9611ae53a92'
image = 'jellyfin/jellyfin'
registry = 'docker.io'
version = '10.11.1'
versioning = 'semver'

[librechat-server]
digest = 'sha256:e6790a1fab2d1870efe077127cc6255cb58105cabde9ec013b8573bfe3025882'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.1-rc1'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:86835e8da0f94efd61334decb320fa43e8a60027688cbd856bf29d065b470338'
image = 'library/mongo'
registry = 'docker.io'
version = '8.2.1'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:86a9b2202f740c1e737b4587de28faa81a131c4c616f832259bcea77096dd6a0'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:8809cfffff0082cf260c9ac752f1dd1afc77f6f0a55c4e6411321e78efc3d9a5'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.0-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mamapi]
digest = 'sha256:9403628e9c0e773c04bb640743105bdbfca53423033828e13d3f5efc79370493'
image = 'elforkhead/mamapi'
registry = 'ghcr.io'
version = 'v2.1.2'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:e1e4832256f5fca895dc3e2f377abfb1476230eb6b30da97fbc32840f21d1e7f'
image = 'foxxmd/multi-scrobbler'
registry = 'docker.io'
version = '0.10.1'
versioning = 'semver'

[paperless-postgresql]
digest = 'sha256:48c8ad3a7284b82be4482a52076d47d879fd6fb084a1cbfccbd551f9331b0e40'
image = 'library/postgres'
registry = 'docker.io'
version = '18.0-alpine'
versioning = 'docker'

[paperless-redis]
digest = 'sha256:59b6e694653476de2c992937ebe1c64182af4728e54bb49e9b7a6c26614d8933'
image = 'library/redis'
registry = 'docker.io'
version = '8.2.2-alpine'
versioning = 'docker'

[paperless-server]
digest = 'sha256:321ca858e4b6ce9dc416dbcb7c0691d545e3e9b0f44cf420f75c22098854ca25'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.19.3'
versioning = 'semver'

[prowlarr]
digest = 'sha256:643220338204525524db787ff38a607261597f49d1f550694acdb3e908e2b43e'
image = 'linuxserver/prowlarr'
registry = 'docker.io'
version = '2.1.5'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:098d4340c0709a9ddbc7010ca21900238388454e20182d52b9723b40a2a44293'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.1.2'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[radarr]
digest = 'sha256:c984533510abe0219a70e80d15bd0d212b7df21baa0913759c4ce6cc9092240b'
image = 'linuxserver/radarr'
registry = 'docker.io'
version = '5.28.0'
versioning = 'semver'

[recyclarr]
digest = 'sha256:759540877f95453eca8a26c1a93593e783a7a824c324fbd57523deffb67f48e1'
image = 'recyclarr/recyclarr'
registry = 'ghcr.io'
version = '7.4.1'
versioning = 'semver'

[sabnzbd]
digest = 'sha256:6e6e7abf7a87436ffccd7df41e64a28df9c530e2be5467339a3f5f0518922b49'
image = 'linuxserver/sabnzbd'
registry = 'docker.io'
version = '4.5.5'
versioning = 'semver'

[sonarr]
digest = 'sha256:fbe67c25693dc5f3de220c5691f374576ae265df782c16918cc071b630490bd7'
image = 'linuxserver/sonarr'
registry = 'docker.io'
version = '4.0.15'
versioning = 'semver'

[zigbee2mqtt]
digest = 'sha256:ffabf256f4550175278fbeebdbc3f174f2ffa005175e755324c5f06020af3e68'
image = 'koenkk/zigbee2mqtt'
registry = 'docker.io'
version = '2.6.2'
versioning = 'semver'