[audiobookshelf]
digest = 'sha256:e23adb24848d99d19cd1e251aee4e1e12ed4f5effc8ccb21754b062b6a06cf66'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.31.0'
versioning = 'semver'

[core-keeper-server]
digest = 'sha256:6531227708c06db6850731609e2df3e0940e63149395c743f12a0ce5f0c34ead'
image = 'escaping/core-keeper-dedicated'
registry = 'docker.io'
version = 'v2.7.0'
versioning = 'semver'

[ente-museum]
digest = 'sha256:980f69321bdda48b91fb86ce54a3060051a3c8da596e7dbea98488c190accac7'
image = 'ente-io/server'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[ente-postgresql]
digest = 'sha256:ed07c2d1032f6119e793251ff0d04f78b39348f13e958682d764a023f735d3f2'
image = 'library/postgres'
registry = 'docker.io'
version = '15.15-alpine'
versioning = 'regex:^(?<major>15)\.(?<minor>\d+)-alpine$'

[ente-web]
digest = 'sha256:1d957709a6e77480f3cd35bcdb06e8b0d1b1e2c4e1a837e629f00b6bc969c644'
image = 'ente-io/web'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[gluetun]
digest = 'sha256:ef4a44819a60469682c7b5e69183e6401171891feaa60186652d292c59e41b30'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.40.3'
versioning = 'semver'

[grist]
digest = 'sha256:5fb6d99b820c60cad9a334a63516ef7e7868aa089815190b95697b8b65db7ae7'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.8'
versioning = 'semver'

[homeassistant]
digest = 'sha256:c9da2a0a5738ceb26e1b4f672825c09371e51ae5e285beffa3072757b7817f3e'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2025.12.3'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:b5f0dfb46e028c156ff4e3dd2908fdf3474e6bd7837902d0e0151e4e30ad711f'
image = 'library/postgres'
registry = 'docker.io'
version = '18.1-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:204825c8cc626a3f44fb4b61f30ca5c76c3b4c557c9fb8bfc719902bf88daae4'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v2.4.0'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:7e2d0df478651551df3358072e68c235200b875eccd6eb4a5c5d8879a7095cf4'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v2.4.0'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[jellyfin]
digest = 'sha256:6d819e9ab067efcf712993b23455cc100ee5585919bb297ea5a109ac00cb626e'
image = 'jellyfin/jellyfin'
registry = 'docker.io'
version = '10.11.5'
versioning = 'semver'

[librechat-server]
digest = 'sha256:36cf6811bc2461ada6879ab299ce32efebfe8b8e0155334161935d72747b9a2e'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.1'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:bf5995bcccb65725aa81fd92e68449323c94b96bf1c1fa9f7acbc2a8ad518114'
image = 'library/mongo'
registry = 'docker.io'
version = '8.2.2'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:48415bc40cbe5c57764f053ef7dbaafcf22ebf5558bd16a1b8eb865d76e4aa96'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:d708f9df030dbd0d7c3d67d349be21acb786d263a5fd92fc12d7b5d2dba49816'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.1-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mamapi]
digest = 'sha256:9403628e9c0e773c04bb640743105bdbfca53423033828e13d3f5efc79370493'
image = 'elforkhead/mamapi'
registry = 'ghcr.io'
version = 'v2.1.2'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:7e2709a4c06e2a8dc8ceeebb5f6d02cc43076b1a0b64bd68e8f868bebc989e19'
image = 'foxxmd/multi-scrobbler'
registry = 'docker.io'
version = '0.10.7'
versioning = 'semver'

[paperless-postgresql]
digest = 'sha256:b5f0dfb46e028c156ff4e3dd2908fdf3474e6bd7837902d0e0151e4e30ad711f'
image = 'library/postgres'
registry = 'docker.io'
version = '18.1-alpine'
versioning = 'docker'

[paperless-redis]
digest = 'sha256:6cbef353e480a8a6e7f10ec545f13d7d3fa85a212cdcc5ffaf5a1c818b9d3798'
image = 'library/redis'
registry = 'docker.io'
version = '8.4.0-alpine'
versioning = 'docker'

[paperless-server]
digest = 'sha256:57ad9565bff3bdf2378ab1dcc21ea649dfd68ee58e0eeca2bfba0120a26563e8'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.20.3'
versioning = 'semver'

[prowlarr]
digest = 'sha256:67a8aaedcfd6989f3030b937a6a07007310b1dfc7ee8df16d2cbfa48d1c1158c'
image = 'linuxserver/prowlarr'
registry = 'docker.io'
version = '2.3.0'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:043498de39c3dd63eec94360c5ad966a51271d1581070f42cb73ab0cf4776f29'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.1.4'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[radarr]
digest = 'sha256:6c0948b42c149e36bb3dbc0b64d36c77b2d3c9dccf1b424c4f72af1e57ba0c21'
image = 'linuxserver/radarr'
registry = 'docker.io'
version = '6.0.4'
versioning = 'semver'

[recyclarr]
digest = 'sha256:2550848d43a453f2c6adf3582f2198ac719f76670691d76de0819053103ef2fb'
image = 'recyclarr/recyclarr'
registry = 'ghcr.io'
version = '7.5.2'
versioning = 'semver'

[sabnzbd]
digest = 'sha256:ed10a7e9fc019aded46f1591f236e9be6d75c99e7017b897b502667cd65afc4c'
image = 'linuxserver/sabnzbd'
registry = 'docker.io'
version = '4.5.5'
versioning = 'semver'

[searxng]
digest = 'sha256:a39ce90965a1650655c10f6e1b83bf0d1f09caf9af3ea182196e53f158f2bc5d'
image = 'searxng/searxng'
registry = 'docker.io'
version = '2025.12.17-896863802'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d{1,2})\.(?<patch>\d{1,2})-(?<build>[a-z0-9]+)$'

[sonarr]
digest = 'sha256:60e5edcac39172294ad22d55d1b08c2c0a9fe658cad2f2c4d742ae017d7874de'
image = 'linuxserver/sonarr'
registry = 'docker.io'
version = '4.0.16'
versioning = 'semver'

[zigbee2mqtt]
digest = 'sha256:163e7351430a95d550d5b1bb958527edc1eff115eb013ca627f3545a192e853f'
image = 'koenkk/zigbee2mqtt'
registry = 'docker.io'
version = '2.7.1'
versioning = 'semver'